export const TIPOS_MOVIMIENTO_BANCARIOS = [
  { value: "pago_iva", label: "PAGO DE IVA" },
  { value: "pago_ica", label: "PAGO DE ICA" },
  { value: "servicios_agua_1p", label: "SERVICIOS PUBLICOS 1 PISO - AGUA" },
  { value: "servicios_luz_1p", label: "SERVICIOS PUBLICOS 1 PISO - LUZ" },
  { value: "servicios_gas_1p", label: "SERVICIOS PUBLICOS 1 PISO - GAS" },
  { value: "arriendo_2p", label: "ARRIENDO 2 PISO" },
  { value: "arriendo_1p", label: "ARRIENDO 1 PISO" },
  { value: "servicios_agua_2p", label: "SERVICIOS PUBLICOS 2 PISO - AGUA" },
  { value: "servicios_luz_2p", label: "SERVICIOS PUBLICOS 2 PISO - LUZ" },
  { value: "servicios_gas_2p", label: "SERVICIOS PUBLICOS 2 PISO - GAS" },
  { value: "domicilios", label: "DOMICILIOS" },
  { value: "insumos", label: "INSUMOS" },
  { value: "movistar_celulares", label: "MOVISTAR- CELULARES" },
  { value: "movistar_internet", label: "MOVISTAR INTERNET" },
  {
    value: "mojica_impresiones",
    label: "MOJICA IMPRESIONES DIGITALES",
  },
  { value: "impresion_litografia", label: "IMPRESIÓN LITOGRAFIA" },
  { value: "acabados", label: "ACABADOS" },
  { value: "pago_dias_trabajo", label: "PAGO X DIAS DE TRABAJO" },
  { value: "pago_nomina_javier", label: "PAGO DE NOMINA JAVIER" },
  { value: "seguridad_social", label: "SEGURIDAD SOCIAL" },
  { value: "creditos_bancos", label: "CREDITOS - BANCOS" },
  {
    value: "gastos_familia_moreno",
    label: "GASTOS FAMILIA MORENO PINEDA",
  },
  { value: "montajes_litograficos", label: "MONTAJES LITOGRAFICOS" },
  { value: "compra_herramienta", label: "COMPRA DE HERRAMIENTA" },
  { value: "pago_nomina_carolina", label: "PAGO DE NOMINA CAROLINA" },
  { value: "pago_nomina_nils", label: "PAGO DE NOMINA NILS" },
  { value: "pago_nomina_edinson", label: "PAGO DE NOMINA EDINSON" },
  { value: "pago_nomina_jerson", label: "PAGO DE NOMINA JERSON" },
  { value: "pago_nomina_yurley", label: "PAGO DE NOMINA YURLEY" },
  { value: "insumos_acrilicos", label: "INSUMOS ACRILICOS" },
  {
    value: "insumos_adhesivos_lonas",
    label: "INSUMOS ADHESIVOS Y LONAS",
  },
  { value: "insumos_electricos", label: "INSUMOS ELECTRICOS" },
  { value: "insumos_mdf", label: "INSUMOS MDF" },
  { value: "servicio_indriver", label: "SERVICIO DE INDRIVER" },
  { value: "servicio_contable", label: "SERVICIO CONTABLE" },
  { value: "insumo_plotter", label: "INSUMO PLOTTER" },
];

export const TIPOS_MOVIMIENTO_BANCARIOS_VALUES = TIPOS_MOVIMIENTO_BANCARIOS.map(
  (tipo) => tipo.value,
);
